### ISSUE TITLE
setup_requires without install_requires not supported by NumPy

### ISSUE THREAD

**Issue by mattip** [astrofrog/fast-histogram#34]
In `setup.py` the build-time dependency on NumPy is defined via a `setup_requires` without an `install_requires`. This is poorly supported, and leads to the following problem on a clean python install
```
pip3 install fast-histogram
python3 -c 'import fast_histogram'
ImportError: No module named 'numpy.core._multiarray_umath'
```
While this might be an issue with Numpy (see numpy/numpy#6599), SciPy solved the problem via scipy/scipy#3566.

**Comment by rgommers** [comment]
@mattip there's an `install_requires` right under `setup_requires`: https://github.com/astrofrog/fast-histogram/blob/master/setup.py#L27. I don't understand this bug report, can you clarify?

**Comment by mattip** [comment]
Sorry, messed up. Closing. Indeed, running the lines in a clean python3.6.6 virtualenv with pip 18.1, I could not reproduce the problem.
