### ISSUE TITLE
bug: invalid memory access

### ISSUE THREAD

**Issue by manodeep** [astrofrog/fast-histogram#4]
The condition in [_histogram1d, line 109](https://github.com/astrofrog/fast-histogram/blob/master/fast_histogram/_histogram_core.c#L109) should probably be `tx < xmax`, otherwise there will be invalid memory access for `tx==xmax` (that would result in `ix==nx`). ~~Similarly for [_histogram2d, line 201](https://github.com/astrofrog/fast-histogram/blob/master/fast_histogram/_histogram_core.c#L201)~~

**Comment by astrofrog** [comment]
Good catch! I had fixed this for the 2D case but forgot about the 1D case.
