### ISSUE TITLE
upstreaming

### ISSUE THREAD

**Issue by amueller** [astrofrog/fast-histogram#42]
Do you have any intention of upstreaming this? I feel like it would be really useful (together with having a ``bincount2d`` which is what I'm usually missing).

**Comment by astrofrog** [comment]
@amueller - see the note here:

https://github.com/astrofrog/fast-histogram#why-not-contribute-this-to-numpy-directly

But in principle I have no objections to including this in Numpy if the Numpy developers are open to it.

**Comment by amueller** [comment]
Thanks :) I probably also don't have the cycles to push this forward, though ;)
