### ISSUE TITLE
return two results

### ISSUE THREAD

**Issue by bastibe** [astrofrog/fast-histogram#7]
`numpy.histogram` returns both counts and edges, while `histogram1d` only returns counts.

**Comment by astrofrog** [comment]
@bastibe - in the interest of performance, would you be ok with having a keyword argument ``return_edges`` that would be ``False`` by default?

**Comment by bastibe** [comment]
Honestly, I would think that numpy compatibility was critical. Also, I would assume that a single `numpy.linspace` will not add any significant performance overhead, especially since the number of edges should at all times be negligible in comparison to the number of data points.

Regardless, it is up to you. I can see that you might not want to introduce backwards-incompatible changes.

**Comment by astrofrog** [comment]
@bastibe - maybe it's fine to break backward-compatibily, after all the package was only released yesterday ;) Would you like to open a pull request?

**Comment by bastibe** [comment]
Sure, will do. It might take a few days, though.

**Comment by astrofrog** [comment]
Ok, I think I'll do it now since I'd rather break API as soon as possible. Will open a PR shortly.

**Comment by astrofrog** [comment]
It turns out this does affect performance signficantly for smaller arrays (< 10^5-6). I'll add a note to the FAQ to explain why we *don't* return the edges :smile:

**Comment by astrofrog** [comment]
See https://github.com/astrofrog/fast-histogram/commit/7eea79ba72d73a5ed02f607b1e7cbc39880941cc

**Comment by bastibe** [comment]
fair enough.
